### ISSUE TITLE
Only works in Wildfly 10

### ISSUE THREAD

**Issue by skroll** [soulwing/wildfly-jgroups-aws-ping#2]
I understand that this module was intended for Wildfly 10 (judging by some cursory google searches), but it should be explicitly stated somewhere in the README. Trying to use this module in Wildfly 9 results in some issues, and requires an older version of the AWS SDK (due to changes in the apache-httpcomponents library).

**Comment by skroll** [comment]
For anyone curious, the following changes are needed for Wildfly 9:
com.amazonaws.core:awsping needs to depend on aws-java-sdk-core-1.10.40, does not require the jmespath or extra jackson dataformat dependency.

com.amazonaws.core:ec2 needs to depend on aws-java-sdk-ec2-1.10.40.

The jgroups-aws module itself needs no changes.

**Comment by ceharris** [comment]
So the only changes you needed to make were to the AWS API version number in the POM and `src/modules/com/amazonaws/core/awsping/module.xml`?

Can probably make it possible to build for either Wildfly 10 or Wildfly 9 using a Maven profile...

**Comment by skroll** [comment]
Yeah, I'm not really familiar with maven as much as I am gradle, so I'm not 100% sure what is necessary. What I did do is push a branch that has the changes, so you can see the diff.

https://github.com/skroll/wildfly-jgroups-aws-ping/tree/wildfly9
