### ISSUE TITLE
Is there additional jgroups-aws configuration needed?

### ISSUE THREAD

**Issue by battmush** [soulwing/wildfly-jgroups-aws-ping#4]
Hi, I'd first like to thank you for the development of this module.  If I can get it working, I can see it solving a large number of issues for my organization.

I've been trying to get this integrated into a Keycloak 9.2 cluster on EC2 nodes (dockerized, but not relevant currently), and am experiencing the following stack trace on start-up:

```
ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 60) MSC000001: Failed to start service org.wildfly.clustering.jgroups.channel.ee: org.jboss.msc.service.StartException in service org.wildfly.clustering.jgroups.channel.ee: java.lang.IllegalStateException: java.io.IOException: failed to get instance identity
[...]
Caused by: java.io.IOException: failed to get instance identity
        at org.jgroups.aws:awsping//com.meltmedia.jgroups.aws.InstanceIdentity.getIdentityDocument(InstanceIdentity.java:77)
        at org.jgroups.aws:awsping//com.meltmedia.jgroups.aws.InstanceIdentity.getIdentity(InstanceIdentity.java:57)
        at org.jgroups.aws:awsping//com.meltmedia.jgroups.aws.AWS_PING.init(AWS_PING.java:179)
[...]
Caused by: java.net.UnknownHostException: instance-data: Name or service not known
        at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
```

I do have the JGROUPS_EXTERNAL_ADDRESS environment variable set, which may or may not be related, here.

Additionally, is there extra jgroups-aws properties that need to be set, set as AWS keys, etc?  Reading that code seems to indicate it's needed for its bootstrapping, though I haven't yet reached that section of init() yet.

Thanks!

**Comment by ceharris** [comment]
Did you see the part in the README where either your EC2 instance role or ECS task role needs to have permission to collect EC2 instance metadata?

**Comment by battmush** [comment]
Yes, and this is set for the instances in question.  I'm able to curl it directly from the instance without problem.

```
$ curl http://169.254.169.254/latest/dynamic/instance-identity/document
{
  "accountId" : "NNN",
  "architecture" : "x86_64",
  "availabilityZone" : "us-east-1a",
  "billingProducts" : null,
  "devpayProductCodes" : null,
  "marketplaceProductCodes" : [ "..." ],
  "imageId" : "ami-dff868a0",
  "instanceId" : "i-NNN",
  "instanceType" : "t2.medium",
  "kernelId" : null,
  "pendingTime" : "2020-06-16T12:16:02Z",
  "privateIp" : "10.185.72.11",
  "ramdiskId" : null,
  "region" : "us-east-1",
  "version" : "2017-09-30"
}
```

I'm now wondering if it is requiring reverse DNS lookup for that IP address?

InstanceIdentity.java:
```
  private static final String INSTANCE_DATA  = System.getProperty("instance.data", "169.254.169.254");
  private static final String INSTANCE_IDENTITY_URL = String.format("http://%s/latest/dynamic/instance-identity/document", INSTANCE_DATA);
```

**Comment by battmush** [comment]
Ah, it appears that the code I was referring to and looking it is in the yet-unreleased 1.7.0 version of jgroups-aws.  In 1.6.1, that code is simply

```
private static String INSTANCE_IDENTITY_URL = "http://instance-data/latest/dynamic/instance-identity/document";
```

I'll try working around it with an /etc/hosts entry for now.

**Comment by battmush** [comment]
That was the solution; from within our AWS VPC the hostname 'instance-data' does not resolve, causing the instance identity discovery to fail.  It looks like a fix for this, to allow the hostname/ip to be supplied by a system property, has been pulled into the jgroups-aws development branch but never released.  Sorry for the interruption!

**Comment by ceharris** [comment]
Glad to learn that you got it sorted!

I updated the README to include your workaround to help others who encounter the same problem.
